[package]
name = "ascii-art"
version = "0.1.0"
authors = ["Ryan Zeigler <zeiglerr@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jpeg-decoder = "0.1.20"
anyhow = "1.0.33"
